<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Build">
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Label="Package">
    <Product>Swashbuckle.AspNetCore.Community.Odata</Product>
    <Description>Provides support for Microsoft.AspNetCore.OData in Swashbuckle</Description>
    <PackageTags>OData;Swashbuckle;Swagger;OpenAPI</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.OData.Core" Version="8.4.3" />
    <PackageReference Include="Microsoft.OData.Edm" Version="8.4.3" />
    <PackageReference Include="Microsoft.OpenApi.OData" Version="3.2.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.7" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.4.1" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.300" />
  </ItemGroup>
  <Target Name="Husky" BeforeTargets="Restore;CollectPackageReferences" Condition="'$(GITHUB_WORKFLOW)' == ''">
    <Exec Command="dotnet tool restore" StandardOutputImportance="Low" StandardErrorImportance="High" />
    <Exec Command="dotnet husky install" StandardOutputImportance="Low" StandardErrorImportance="High" WorkingDirectory="..\.." />
  </Target>
</Project>